apiVersion: v1
kind: Secret
metadata:
  name: github-ssh-creds-secret
  namespace: tekton-pipelines
data:
  id_rsa: <top-secret>
  known_hosts: <top-secret>
  config: <top-secret>
---

apiVersion: v1
kind: Secret
metadata:
  name: website-reg-cred
  namespace: tekton-pipelines
data:
  config.json: <top-secret>
---

apiVersion: v1
kind: Secret
metadata:
  name: website-sonar-settings
  namespace: tekton-pipelines
data:
  sonar-project.properties: |
    sonar.projectKey=intensa
    sonar.projectVersion=1.0
    sonar.sourceEncoding=UTF-8
    sonar.host.url=https://sonar.local
    sonar.sources=src
    sonar.visualstudio.enable=true
    sonar.login=sonar
    sonar.password=password

