apiVersion: triggers.tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: intensa-pipeline-listener
  namespace: tekton-pipelines
spec:
  serviceAccountName: intensa-pipeline-trigger-sa
  triggers:
    - name: intensa-ng-client-pipeline-trigger
      # github event payload description
      # https://support.atlassian.com/github-cloud/docs/event-payloads/
      # Expressions tutorial
      # https://tekton.dev/vault/triggers-v0.6.1/cel_expressions/#list-of-extensions
      interceptors:
        - cel:
            filter: "body.pullrequest.state.contains('MERGED') && body.pullrequest.source.repository.name.contains('intensa-frontend')"
            overlays:
              - key: webhook_uuid
                expression: "header.canonical('X-Hook-UUID')"
              - key: truncated_commit_sha
                expression: "body.pullrequest.merge_commit.hash.truncate(7)"
              - key: commit_date
                expression: "body.pullrequest.updated_on.truncate(10)"
      bindings:
        - ref: intensa-ng-client-pipeline-binding
      template:
        ref: intensa-ng-client-pipeline-template
    - name: intensa-api-pipeline-trigger
      interceptors:
        - cel:
            filter: "body.pullrequest.state.contains('MERGED') && body.pullrequest.source.repository.name.contains('intensa-backend')"
            overlays:
              - key: webhook_uuid
                expression: "header.canonical('X-Hook-UUID')"
              - key: truncated_commit_sha
                expression: "body.pullrequest.merge_commit.hash.truncate(7)"
              - key: commit_date
                expression: "body.pullrequest.updated_on.truncate(10)"
      bindings:
        - ref: intensa-api-pipeline-binding
      template:
        ref: intensa-api-pipeline-template

# Client fronted app
---
apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerBinding
metadata:
  name: intensa-ng-client-pipeline-binding
  namespace: tekton-pipelines
spec:
  params:
    - name: git-revision
      value: $(extensions.truncated_commit_sha)
    - name: git-repository-url
      value: $(body.repository.links.html.href)
    - name: commit-date
      value: $(extensions.commit_date)
---
apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: intensa-ng-client-pipeline-template
  namespace: tekton-pipelines
spec:
  params:
    - name: git-revision
      description: The git revision
      default: master
    - name: git-repository-url
      description: The git repository url
    - name: commit-date
      description: commit date
  resourcetemplates:
    - apiVersion: tekton.dev/v1beta1
      kind: PipelineRun
      metadata:
        generateName: triggered-intensa-ng-client-pipelinerun-
      spec:
        pipelineRef:
          name: intensa-ng-client-pipeline
        params:
          - name: gitUrl
            value: git@github.com:RepoOwner/intensa-frontend.git
          - name: infraGitUrl
            value: git@github.com:RepoOwner/intensa-infra.git
          - name: branchName
            value: master
          - name: infraBranchName
            value: master
          - name: imageUrl
            value: registry.website.ru/intensa/ng-client
          - name: imageTag
            value: v0.0.1-$(tt.params.commit-date)-$(tt.params.git-revision)
          - name: pathToContext
            value: ""
          - name: sonar-url
            value: https://sonar.website.ru
          - name: sonar-project-name
            value: intensa-ng-client
        serviceAccountName: intensa-pipeline-account
        workspaces:
          - name: git-source
            volumeClaimTemplate:
              spec:
                accessModes:
                  - ReadWriteOnce
                resources:
                  requests:
                    storage: 1Gi
          - name: git-infra-source
            volumeClaimTemplate:
              spec:
                accessModes:
                  - ReadWriteOnce
                resources:
                  requests:
                    storage: 100Mi
          - name: ssh-creds
            secret:
              secretName: github-ssh-creds-secret
          - name: ssh-w-creds
            secret:
              secretName: github-ssh-w-creds-secret
          - name: dockerconfig
            secret:
              secretName: website-reg-cred
          - name: sonar-settings
            secret:
              secretName: website-sonar-settings
---
# API
apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerBinding
metadata:
  name: intensa-api-pipeline-binding
  namespace: tekton-pipelines
spec:
  params:
    - name: git-revision
      value: $(extensions.truncated_commit_sha)
    - name: git-repository-url
      value: $(body.repository.links.html.href)
    - name: commit-date
      value: $(extensions.commit_date)
---
apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: intensa-api-pipeline-template
  namespace: tekton-pipelines
spec:
  params:
    - name: git-revision
      description: The git revision
      default: master
    - name: git-repository-url
      description: The git repository url
    - name: commit-date
      description: commit date
  resourcetemplates:
    - apiVersion: tekton.dev/v1beta1
      kind: PipelineRun
      metadata:
        generateName: triggered-intensa-api-pipelinerun-
      spec:
        pipelineRef:
          name: intensa-api-pipeline
        params:
          - name: gitUrl
            value: git@github.com:RepoOwner/intensa-backend.git
          - name: infraGitUrl
            value: git@github.com:RepoOwner/intensa-infra.git
          - name: branchName
            value: master
          - name: infraBranchName
            value: master
          - name: imageUrl
            value: registry.website.ru/intensa/api
          - name: imageTag
            value: v0.0.1-$(tt.params.commit-date)-$(tt.params.git-revision)
          - name: pathToContext
            value: ""
          - name: sonar-url
            value: https://sonar.website.ru
          - name: sonar-project-name
            value: intensa-api
        serviceAccountName: intensa-pipeline-account
        workspaces:
          - name: git-source
            volumeClaimTemplate:
              spec:
                accessModes:
                  - ReadWriteOnce
                resources:
                  requests:
                    storage: 1Gi
          - name: git-infra-source
            volumeClaimTemplate:
              spec:
                accessModes:
                  - ReadWriteOnce
                resources:
                  requests:
                    storage: 100Mi
          - name: ssh-creds
            secret:
              secretName: github-ssh-creds-secret
          - name: ssh-w-creds
            secret:
              secretName: github-ssh-w-creds-secret
          - name: dockerconfig
            secret:
              secretName: website-reg-cred
          - name: sonar-settings
            secret:
              secretName: website-sonar-settings
